"""
Layer 4: AI Risk Narrative Generation using Gemini API.

This module provides an explainable decision-support layer for tax compliance analysts.
It explains already-validated risk signals produced by Layers 1, 2, and 3.

CRITICAL DESIGN PRINCIPLES:
1. EXPLANATION ONLY: Does NOT detect fraud, modify risk scores, recalculate metrics,
   or alter assigned risk tiers.
2. DETERMINISTIC INTEGRITY: Layers 1-3 remain completely authoritative.
3. STRUCTURED OUTPUT: All outputs adhere strictly to the RiskNarrative schema.
4. EVIDENCE GROUNDED: Explanations and investigation priorities reference only validated facts.
5. OPTIONAL & RESILIENT: API failures or missing keys gracefully degrade without failing
   upstream pipelines.
"""

import json
import logging
import os
import re
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError

load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger("Layer4_AI_Risk_Narrative")


def sanitize_log_message(msg: Any) -> str:
    """Mask potential API keys, passwords, and sensitive tokens from log messages."""
    text = str(msg)
    # Redact Google/Gemini API keys
    text = re.sub(r'AIza[0-9A-Za-z-_]{10,}', '[REDACTED_API_KEY]', text)
    text = re.sub(r'AQ\.[0-9A-Za-z-_]{10,}', '[REDACTED_API_KEY]', text)
    # Redact key/password patterns with := or spaces or phrases
    text = re.sub(
        r'(api[-_]?key|key|password|passwd|pass|secret|token)\s*(?:[:=]|is|\s)\s*[^\s,;]+',
        r'\1=[REDACTED]',
        text,
        flags=re.IGNORECASE
    )
    # Redact user credentials in database URIs
    text = re.sub(r':([^:@\s]+)@', ':***@', text)
    return text

# ── Pydantic Schema for Structured Response ──────────────────────────

class RiskNarrative(BaseModel):
    """Structured risk narrative generated by Gemini."""
    risk_summary: str = Field(
        description="Concise explanation of the vendor's validated risk profile based strictly on observed signals."
    )
    key_drivers: List[str] = Field(
        description="List of primary validated risk drivers contributing to the deterministic score."
    )
    investigation_priorities: List[str] = Field(
        description="Concrete, prioritized recommendations for tax/audit investigators based only on supplied evidence."
    )
    evidence: List[str] = Field(
        description="Specific quantitative metrics and flag facts directly cited from the input."
    )


# ── System Instruction Guardrails ───────────────────────────────────

SYSTEM_INSTRUCTION = """You are a specialized GST Tax Risk Explanation Agent acting as an explainable decision-support layer for tax compliance analysts and auditors.

CRITICAL OPERATIONAL BOUNDARIES:
1. EXPLANATION LAYER ONLY: You explain existing, already-validated risk signals.
2. AUTHORITATIVE UPSTREAM SCORING: All risk scores and tiers were deterministically calculated by upstream rule-based and statistical models (Layers 1, 2, and 3). You must NEVER modify, recalculate, or reinterpret numerical scores or assigned risk tiers.
3. NO FRAUD ACCUSATIONS: You must NEVER claim that a vendor or taxpayer committed fraud, tax evasion, or criminal intent. Frame all findings strictly as observed anomalies, statistical deviations, or validation mismatches that warrant investigation.
4. EVIDENCE GROUNDED: Distinguish verified evidence from interpretation. Reference ONLY facts, counts, ratios, and metrics provided in the vendor evidence payload.
5. NO HALLUCINATIONS: Do NOT invent missing details, invoice numbers, dates, or business activities. If certain details cannot be determined from the evidence, explicitly state that.
6. INVESTIGATION PRIORITIES: Prioritize actionable, evidence-based review steps for tax investigators based solely on the supplied flags.
"""


def parse_risk_tiers(raw_tiers: Optional[str] = None) -> List[str]:
    """Parse comma-separated risk tiers from environment or argument.

    Defaults to ['HIGH'].
    Supports e.g. 'HIGH', 'HIGH,MEDIUM', 'HIGH, MEDIUM'.
    """
    if raw_tiers is None:
        raw_tiers = os.getenv("AI_RISK_TIERS", "HIGH")
    tiers = [t.strip().upper() for t in raw_tiers.split(",") if t.strip()]
    return tiers if tiers else ["HIGH"]


def build_user_prompt(vendor_data: Dict[str, Any]) -> str:
    """Construct an evidence-grounded prompt containing only deterministic signals."""
    flag_breakdown = vendor_data.get("flag_breakdown", [])
    if flag_breakdown:
        breakdown_str = "\n".join(
            f"  - {item['flag_type']} (Severity: {item['severity']}): {item['flag_count']} occurrence(s)"
            for item in flag_breakdown
        )
    else:
        breakdown_str = "  - None recorded"

    prompt = f"""Generate a structured risk explanation narrative for the following vendor based strictly on the validated evidence below.

VENDOR PROFILE & DETERMINISTIC RISK SIGNALS:
- Vendor ID: {vendor_data.get('vendor_id')}
- Vendor Name: {vendor_data.get('vendor_name')}
- Category: {vendor_data.get('category')}
- Registered State Code: {vendor_data.get('state_code')}
- Deterministic Risk Tier: {vendor_data.get('risk_tier')} (Authoritative)
- Composite Risk Score: {vendor_data.get('composite_score')} / 100.0 (Authoritative)

COMPONENT SIGNALS (Layer 3 Normalized 0-100):
- Anomaly Frequency Score: {vendor_data.get('anomaly_frequency')} / 100.0
- Deviation Magnitude Score: {vendor_data.get('deviation_magnitude')} / 100.0
- Validation Failures Score: {vendor_data.get('validation_failures')} / 100.0
- Recency Score: {vendor_data.get('recency_score')} / 100.0

INVOICE & ANOMALY METRICS:
- Total Invoices: {vendor_data.get('total_invoices')}
- Flagged Invoices: {vendor_data.get('flagged_invoices')}
- Invoice Flag Rate: {vendor_data.get('flag_rate')}%
- Validated Flag Breakdown:
{breakdown_str}

REQUIREMENTS:
- Synthesize the observed signals into an analyst-friendly risk summary.
- List key drivers directly supported by the data.
- Propose specific, prioritized investigation steps without accusing the vendor of fraud.
- Cite specific metrics in the evidence section.
"""
    return prompt


def init_narrative_table(conn) -> None:
    """Ensure the ai_risk_narratives table exists in PostgreSQL."""
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS ai_risk_narratives (
        narrative_id             SERIAL PRIMARY KEY,
        vendor_id                INT REFERENCES vendors(vendor_id),
        risk_tier                VARCHAR(10) NOT NULL,
        composite_score          DECIMAL(5,2) NOT NULL,
        risk_summary             TEXT NOT NULL,
        key_drivers              TEXT[] NOT NULL,
        investigation_priorities TEXT[] NOT NULL,
        evidence                 TEXT[] NOT NULL,
        model_name               VARCHAR(50) NOT NULL,
        generated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    """
    with conn.cursor() as cur:
        cur.execute(create_table_sql)
    conn.commit()


def fetch_vendors_for_narrative(conn, tiers: List[str]) -> List[Dict[str, Any]]:
    """Fetch deterministic vendor risk scoring results and flag evidence from DB."""
    query = """
        SELECT
            vr.vendor_id,
            v.vendor_name,
            v.category,
            v.state_code,
            vr.anomaly_frequency,
            vr.deviation_magnitude,
            vr.validation_failures,
            vr.recency_score,
            vr.composite_score,
            vr.risk_tier,
            COUNT(DISTINCT i.invoice_id) AS total_invoices,
            COUNT(DISTINCT f.invoice_id) AS flagged_invoices,
            ROUND(
                COUNT(DISTINCT f.invoice_id) * 100.0 / NULLIF(COUNT(DISTINCT i.invoice_id), 0),
                2
            ) AS flag_rate
        FROM vendor_risk_scores vr
        JOIN vendors v ON vr.vendor_id = v.vendor_id
        LEFT JOIN invoices i ON vr.vendor_id = i.vendor_id
        LEFT JOIN flags f ON vr.vendor_id = f.vendor_id
        WHERE vr.risk_tier = ANY(%s)
        GROUP BY
            vr.vendor_id, v.vendor_name, v.category, v.state_code,
            vr.anomaly_frequency, vr.deviation_magnitude,
            vr.validation_failures, vr.recency_score,
            vr.composite_score, vr.risk_tier
        ORDER BY vr.composite_score DESC;
    """
    vendors = []
    with conn.cursor() as cur:
        cur.execute(query, (tiers,))
        rows = cur.fetchall()

        for row in rows:
            vendor_id = row[0]
            # Fetch flag breakdown for this vendor
            cur.execute("""
                SELECT flag_type, severity, COUNT(*) AS flag_count
                FROM flags
                WHERE vendor_id = %s
                GROUP BY flag_type, severity
                ORDER BY flag_count DESC;
            """, (vendor_id,))
            breakdown = [
                {"flag_type": f[0], "severity": f[1], "flag_count": f[2]}
                for f in cur.fetchall()
            ]

            vendor_data = {
                "vendor_id": row[0],
                "vendor_name": row[1],
                "category": row[2],
                "state_code": row[3],
                "anomaly_frequency": float(row[4]) if row[4] is not None else 0.0,
                "deviation_magnitude": float(row[5]) if row[5] is not None else 0.0,
                "validation_failures": float(row[6]) if row[6] is not None else 0.0,
                "recency_score": float(row[7]) if row[7] is not None else 0.0,
                "composite_score": float(row[8]) if row[8] is not None else 0.0,
                "risk_tier": row[9],
                "total_invoices": int(row[10]) if row[10] is not None else 0,
                "flagged_invoices": int(row[11]) if row[11] is not None else 0,
                "flag_rate": float(row[12]) if row[12] is not None else 0.0,
                "flag_breakdown": breakdown,
            }
            vendors.append(vendor_data)

    return vendors


def generate_vendor_narrative(
    client: Any,
    vendor_data: Dict[str, Any],
    model_name: str
) -> Optional[RiskNarrative]:
    """Call Gemini to generate a structured risk narrative for a vendor."""
    from google.genai import types

    user_prompt = build_user_prompt(vendor_data)

    try:
        config = types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            response_mime_type="application/json",
            response_schema=RiskNarrative,
            temperature=0.2,
        )

        response = client.models.generate_content(
            model=model_name,
            contents=user_prompt,
            config=config,
        )

        raw_text = getattr(response, "text", None)
        if not raw_text:
            logger.warning(
                f"Empty response from Gemini for vendor {vendor_data.get('vendor_id')}."
            )
            return None

        # Parse and validate with Pydantic
        narrative = RiskNarrative.model_validate_json(raw_text)
        return narrative

    except ValidationError as ve:
        logger.error(
            f"Schema validation failed for vendor {vendor_data.get('vendor_id')}: {sanitize_log_message(ve)}"
        )
        return None
    except json.JSONDecodeError as je:
        logger.error(
            f"Malformed JSON returned for vendor {vendor_data.get('vendor_id')}: {sanitize_log_message(je)}"
        )
        return None
    except Exception as e:
        logger.error(
            f"Gemini API invocation failed for vendor {vendor_data.get('vendor_id')}: {sanitize_log_message(e)}"
        )
        return None


def store_narrative(
    conn,
    vendor_data: Dict[str, Any],
    narrative: RiskNarrative,
    model_name: str
) -> None:
    """Store generated narrative into ai_risk_narratives table."""
    insert_sql = """
    INSERT INTO ai_risk_narratives (
        vendor_id, risk_tier, composite_score,
        risk_summary, key_drivers, investigation_priorities,
        evidence, model_name
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s);
    """
    with conn.cursor() as cur:
        # Remove any prior narrative for this vendor to ensure idempotence
        cur.execute("DELETE FROM ai_risk_narratives WHERE vendor_id = %s", (vendor_data["vendor_id"],))
        cur.execute(
            insert_sql,
            (
                vendor_data["vendor_id"],
                vendor_data["risk_tier"],
                vendor_data["composite_score"],
                narrative.risk_summary,
                narrative.key_drivers,
                narrative.investigation_priorities,
                narrative.evidence,
                model_name,
            ),
        )
    conn.commit()


def run_layer4(
    conn=None,
    api_key: Optional[str] = None,
    model_name: Optional[str] = None,
    risk_tiers: Optional[str] = None
) -> List[Dict[str, Any]]:
    """Execute Layer 4: AI Risk Narrative Generation.

    This function is fully fail-safe: any failure in API key resolution,
    Gemini communication, or database operations is captured, logged,
    and returns gracefully without throwing exceptions or corrupting
    upstream results.
    """
    print("=" * 50)
    print("LAYER 4 — AI RISK NARRATIVE (GEMINI DECISION-SUPPORT)")
    print("=" * 50)

    # 1. Resolve API Key
    effective_api_key = api_key or os.getenv("GEMINI_API_KEY")
    if not effective_api_key or effective_api_key.strip() == "":
        logger.warning(
            "GEMINI_API_KEY is not set. Skipping AI risk narrative generation. "
            "Upstream deterministic scores remain authoritative and unaffected."
        )
        print("⚠️  GEMINI_API_KEY missing. Layer 4 skipped gracefully.")
        return []

    # 2. Resolve Model and Tiers
    effective_model = model_name or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    target_tiers = parse_risk_tiers(risk_tiers)
    print(f"  Configuration:")
    print(f"    Model       : {effective_model}")
    print(f"    Target Tiers: {', '.join(target_tiers)}")

    # 3. Initialize Gemini Client
    try:
        from google import genai
        client = genai.Client(api_key=effective_api_key)
    except Exception as e:
        logger.error(f"Failed to initialize Gemini client: {sanitize_log_message(e)}")
        print(f"⚠️  Could not initialize Gemini client: {sanitize_log_message(e)}. Skipping Layer 4.")
        return []

    # 4. Resolve Database Connection
    should_close_conn = False
    if conn is None:
        try:
            import psycopg2
            db_host = os.getenv("DB_HOST", "localhost")
            db_port = os.getenv("DB_PORT", "5432")
            db_name = os.getenv("DB_NAME", "gst_analytics")
            db_user = os.getenv("DB_USER", "postgres")
            db_password = os.getenv("DB_PASSWORD")

            conn = psycopg2.connect(
                dbname=db_name,
                user=db_user,
                password=db_password,
                host=db_host,
                port=db_port
            )
            should_close_conn = True
        except Exception as e:
            logger.error(f"Could not connect to database for Layer 4: {sanitize_log_message(e)}")
            print(f"⚠️  Database connection failed: {sanitize_log_message(e)}. Skipping Layer 4.")
            return []

    results = []
    try:
        init_narrative_table(conn)
        vendors = fetch_vendors_for_narrative(conn, target_tiers)
        print(f"\n  Found {len(vendors)} vendor(s) matching tier(s) {target_tiers} for narrative generation.")

        success_count = 0
        failure_count = 0

        for idx, vendor in enumerate(vendors, 1):
            vid = vendor["vendor_id"]
            vname = vendor["vendor_name"]
            score = vendor["composite_score"]
            tier = vendor["risk_tier"]

            print(f"  [{idx}/{len(vendors)}] Generating narrative for Vendor {vid} ({vname}) - Score: {score} [{tier}]...")
            narrative = generate_vendor_narrative(client, vendor, effective_model)

            if narrative:
                try:
                    store_narrative(conn, vendor, narrative, effective_model)
                    success_count += 1
                    results.append({
                        "vendor_id": vid,
                        "vendor_name": vname,
                        "risk_tier": tier,
                        "composite_score": score,
                        "narrative": narrative.model_dump(),
                    })
                except Exception as store_err:
                    logger.error(f"Failed to store narrative for vendor {vid}: {sanitize_log_message(store_err)}")
                    failure_count += 1
            else:
                failure_count += 1

        print("\n" + "=" * 50)
        print("LAYER 4 SUMMARY")
        print("=" * 50)
        print(f"  Target Vendors Evaluated: {len(vendors)}")
        print(f"  Narratives Generated    : {success_count}")
        print(f"  Failed / Skipped        : {failure_count}")
        print("✅ Layer 4 execution complete.")

    except Exception as e:
        logger.error(f"Unexpected error during Layer 4 pipeline execution: {sanitize_log_message(e)}")
        print(f"⚠️  Layer 4 encountered an error: {sanitize_log_message(e)}. Upstream pipeline remains unaffected.")
    finally:
        if should_close_conn and conn:
            try:
                conn.close()
            except Exception:
                pass

    return results


if __name__ == "__main__":
    run_layer4()
